coverage:
  ignore:
    - "coverage_results.txt"
  status:
    project:
      default:
        # The build fails if total project coverage drops by more than 6%
        target: auto
        threshold: "6%"
    changes: false
    patch: false
