= FLUIDIntegrates
:lang:                   es
:author:                 Enginering Team
:email:		         engineering@fluidattacks.com
:revnumber:              v1.0
:revdate:                2017
:toc:                    macro
:toc-title:              Table of Contents
:icons:                  font
:source-highlighter:     pygments
:keywords:               fluidintegrates, fluidattacks,

image:https://gitlab.com/fluidattacks/integrates/badges/master/pipeline.svg[link="https://gitlab.com/fluidattacks/integrates/commits/master",title="pipeline status"]
image:https://gitlab.com/fluidattacks/integrates/badges/master/coverage.svg[link="https://gitlab.com/fluidattacks/integrates/commits/master",title="coverage report"]

toc::[]

== Application

The instructions presented below have been verified in the
following Debian based operating systems:

* Ubuntu 16.04.1 LTS aka LTS

[source, console]
----
$ lsb_release -a.
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:    16.04
Codename:   xenial
----

<<<
== Packages update

* For a correct installation and avoid incompatibility in the versions of the
  dependencies, it is necessary to update essentials packages of the
  environment. For operating systems based on *Debian* the update commands are:

[source, console]
----
$ sudo apt-get update \
               upgrade

----

<<<
== Dependencies

* First step to contribute in Integrates development is to install some tools
  in the operating system that allow to have a proper develop environment.
  For operating systems based on *Debian*, the command that
  installs these dependencies is:

[source, console]
----
$ sudo apt install git \
                   python \
                   python-pip \
                   apache2 \
                   libapache2-mod-wsgi \
                   direnv \
                   ruby

----

* The following library must be installed individually with the command:

[source, console]
----
$ sudo apt install libapache2-mod-wsgi-py3

----

  * NOTE:

  For UBUNTU distirbutions >= 14.04:

* It is necessary that *_pip_* is updated in the latest version,
  for this you must execute the following command:

[source, console]
----
$ pip install --upgrade pip

----

* Then, you need to install the following dependenciess:

[source, console]
----
$ sudo apt install libtiff5-dev \
                   libjpeg8-dev \
                   zlib1g-dev \
                   libfreetype6-dev \
                   liblcms2-dev \
                   libwebp-dev \
                   tcl8.6-dev \
                   tk8.6-dev \
                   python-tk

----

* Finally, we install the necessary complements for the correct
  python operation:

[source, console]
----
$ sudo pip install  django \
                    requests \
                    openpyxl \
                    lxml \
                    python-pptx \
                    pyyaml \
                    decorators \
                    retrying

----

<<<
== Download

* In this stage, we proceed to create a local branch of main Integrates
  repository in a specific system folder:

[source, console]
----
$ cd /var/www && sudo git clone https://gitlab.com/fluidattacks/integrates.git
Cloning into 'integrates'...
Username for 'https://gitlab.com': loginatfluid
Password for 'https://loginatfluid@gitlab.com':
remote: Counting objects: 5858, done.
remote: Compressing objects: 100% (93/93), done.
remote: Total 5858 (delta 82), reused 148 (delta 69)
Receiving objects: 100% (5858/5858), 29.56 MiB | 679.00 KiB/s, done.
Resolving deltas: 100% (3243/3243), done.
Checking connectivity... done.

----

<<<
== GIT configuration

* To start making changes to the repository, you must configure the
   user with whom your changes will be registered:

[source, console]
----
$ git config --global user.name "Faustino Asprilla"
$ git config --global user.email fasprilla@fluidattacks.com
----

* You can check if the changes were successfully registered with:

[source, console]
----
$ git config --list
user.email=fasprilla@fluidattacks.com
user.name=Faustino Asprilla
alias.ahead=log origin/master..HEAD --oneline
push.default=matching
----

<<<
== Deploy FLUIDintegrates locally

* Before any merge request, it is necessary to verify that changes we are going
  to make work correctly and do not interfer with the good operation of the
  rest of code. This can be verified when you deploy the app locally, which can
  be achieved through the following commands:

[source, console]
----
$ sudo  mkdir  /usr/src/app  && cd /usr/src/app
$ sudo ln -s /var/www/integrates/* .

----

*  Install other dependencies, that are a minimum requirement to deploy
   FLUIDIntegrates, with command:

[source, console]
----
$ sudo apt install ansible
$ sudo apt-get install libmysqlclient-dev \
                       build-essential \
                       libssl-dev \
                       libffi-dev \
                       python-dev

----

* Missing dependencies will be installed and those that are
  already installed will be updated:

[source, console]
----
$ sudo apt-get install -y python-dev python-pip
$ sudo gem install asciidoctor-pdf --pre
$ cd /var/www/integrates/deploy/containers/deps && sudo pip install --upgrade -r requirements.txt

----

* The previous command is essential for deployment, so you should ensure that
  the installation is correct (without error messages or not updated
  dependencies)

<<<
== NPM Installation
* Node Package Manager or simply npm is a package manager from which we can have
  any library available with just one line of code, npm will help us manage our
  modules, distribute packages and add dependencies in a simple way.
  To install npm we must install _Nodejs_ and _npm_:

[source, console]
----
$ sudo apt-get install curl
$ curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
$ sudo apt-get install -y nodejs
$ sudo apt-get install -y npm

----

* To install the dependencies that are already in FLUIDIntegrates,
  execute the following command:

[source, console]
----
$ cd app/assets
$ npm install

----

* To install new dependencies or packages, the following command must be
  executed:

[source, console]
----
$ cd app/assets
$ npm install <package_name> --save

----

* To delete dependencies or packages that will no longer be used:

[source, console]
----
$ cd app/assets
$ npm uninstall <package_name> --save

----

* To see more information about npm packages, visit the following
link: _https://www.npmjs.com/_.

<<<
== Environment variables for Integrates

Integrates relies on an external service (`Vault`)
to obtain all the `API` credentials and secret variables
used to succesfully run the application.
To be able to access the secrets, the following steps are required:

. Download link:https://www.vaultproject.io/downloads.html[`Vault`],
according to the `OS` running in the computer.
Once downloaded, make the executable available at the `PATH`.

. Open the file `$HOME/.bashrc` or the equivalent in your shell of preference
and append the following command:
+
[source, bash]
----
$ export VAULT_ADDR=https://vault.fluidattacks.com
----

. Then load the previous variable with the following command:
+
[source, bash]
----
$ source $HOME/.bashrc
----

. Now you can authenticate against `Vault`,
which uses the `RADIUS` protocol connected to `OneLogin`,
so the credentials are the same ones used for `OneLogin`.
+
[source, bash]
----
$ vault login -method=radius username=user@fluidattacks.com

Password: password+OTP (not including the '+')
----

. Download the link:https://drive.google.com/open?id=1LO2bPr36oLyOHDUEPEaJd5OdslWJAZnm[Certificate]
used to establish a `TLS` communication with `Vault`.
To install the certificate, run the following commands:
+
[source, bash]
----
$ sudo mv vault-ca.crt /usr/local/share/ca-certificates/
$ sudo update-ca-certificates
----

. Download and install `virtualenv`, tool used to export
the variables stored in `Vault` as environmental variables
to the process which will run `Integrates`.
+
[source, bash]
----
$ curl -LsSo vaultenv.deb https://github.com/channable/vaultenv/releases/download/v0.7.1/vaultenv-0.7.1.deb \
     && sudo dpkg -i vaultenv.deb \
     && rm vaultenv.deb
----

== Compile `front-end` files

Front-end files are written in `TypeScript` and
must be compiled using `gulp`, in order to generate a `bundle.min.js` file,
it can be done following the next commands:
+
[source, bash]
----
$ cd /var/www/integrates/front && sudo apt-get install -y gulp
$ sudo npm install
$ sudo gulp package:dev
----

== Deploy server

* Finally you must launch the local server that contains the application. This
  can be done in 2 ways:

=== 1. Deploy server with Python

* Save the following code to a script called `local-test.sh`
and make it executable
+
[source, console]
----
#!/usr/bin/env bash
set -e

export FI_DRIVE_AUTHORIZATION=$(vault read -field=drive_authorization secret/integrates/development | base64 --decode)
export FI_DRIVE_AUTHORIZATION_CLIENT=$(vault read -field=drive_authorization_client secret/integrates/development | base64 --decode)
export FI_DOCUMENTROOT=$(vault read -field=documentroot secret/integrates/development)

$(which python) /var/www/integrates/deploy/containers/common/vars/render.py

unset FI_DRIVE_AUTHORIZATION
unset FI_DRIVE_AUTHORIZATION_CLIENT
unset FI_DOCUMENTROOT

export VAULT_HOST='vault.fluidattacks.com'
export VAULT_PORT=443
export VAULTENV_SECRETS_FILE=/var/www/integrates/env-dev.vars
export VAULT_TOKEN="$(cat ~/.vault-token)"

if [ ! -f '/var/www/integrates/env-dev.vars' ]; then
  sed 's/env#/development#/g' /var/www/integrates/env.vars \
    > /var/www/integrates/env-dev.vars
fi

vaultenv $(which python) manage.py runsslserver
----

* Execute the script
+
[source, bash]
----
$ chmod a+x local-test.sh
$ ./local-test.sh
----

* At this point the application is already displayed locally. To access it go to
  the address bar of your browser and write the following address:
  _https: // localhost: 8000_.

=== 1. Deploy server with Docker

* The first thing to do is install Docker CE. Follow the installation steps that are found
  https://docs.docker.com/install/linux/docker-ce/debian/#install-using-the-convenience-script[here].

* Execute the following command, which will ask you to enter a username and
  password corresponding to your credentials in Gitlab.

[source, console]
----
$ sudo docker login registry.gitlab.com -u $DOCKER_USER -p $DOCKER_PASS

----
* Branch name of Integrates repository that will be cloned inside the container
  must be specified, usually the _master_ branch is cloned.

[source, console]
----
$ CI_COMMIT_REF_NAME=master

----

* Before launching the container, it is necessary to create the image that will
  be used during deployment.

[source, console]
----
$ sh build.sh $CI_COMMIT_REF_NAME $FI_GITLAB_LOGIN $FI_GITLAB_PASSWORD $FI_DRIVE_AUTHORIZATION $FI_DOCUMENTROOT $FI_SSL_CERT $FI_SSL_KEY

----

* To deploy the server, the following command is executed:

[source, console]
----
$ sudo docker run -d -p 8000:443 --env-file /var/www/integrates/env.list -t --name=integrates registry.gitlab.com/fluidattacks/integrates:base

----

* At this point the application is already displayed locally. To access it go to
  the address bar of your browser and write the following address:
  _https: // localhost: 8000_.
