= FLUIDIntegrates
:lang:                   es
:author:                 Enginering Team
:email:		         engineering@fluidattacks.com
:revnumber:              v1.0
:revdate:                2017
:toc:                    macro
:toc-title:              Tabla de Contenido
:icons:                  font
:source-highlighter:     pygments
:keywords:               fluidintegrates, fluidsignal,

image:https://gitlab.com/fluidsignal/integrates/badges/master/pipeline.svg[link="https://gitlab.com/fluidsignal/integrates/commits/master",title="pipeline status"]
image:https://gitlab.com/fluidsignal/integrates/badges/master/coverage.svg[link="https://gitlab.com/fluidsignal/integrates/commits/master",title="coverage report"]

toc::[]

== Aplicación

Las instrucciones que se presentan a continuación han sido verificadas en los
siguientes sistemas operativos basados en Debian:

* Ubuntu 16.04.1 LTS aka LTS

[source, console]
----
$ lsb_release -a.
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:    16.04
Codename:   xenial
----

<<<
== Actualización de paquetes

* Para una correcta instalación de la aplicación y evitar incompatibilidad
  en las versiones de las dependencias, es necesario actualizar los paquetes
  esenciales del ambiente.  Para sistemas operativos basados en *Debian* los
  comandos   que actualiza estas dependencias es el siguiente:

[source, console]
----
$ sudo apt-get update \
               upgrade

----

<<<
== Dependencias

* Lo primero para comenzar a contribuir en el desarrollo es instalar algunas
  herramientas dentro del sistema operativo que permiten tener un ambiente de
  desarrollo idoneo.  Para sistemas operativos basados en *Debian* el comando
  que instala estas dependencias es el siguiente:

[source, console]
----
$ sudo apt install git \
                   python \
                   python-pip \
                   apache2 \
                   libapache2-mod-wsgi \
                   direnv \
                   ruby

----

* La siguiente libreria debe ser instalada de forma individual con el siguiente
  comando:

[source, console]
----
$ sudo apt install libapache2-mod-wsgi-py3

----

  * NOTA:

  Para distirbuciones UBUNTU >= 14.04:

* Es necesario que el comando *_pip_* esté actualizado en la versión más reciente,
  para esto se debe ejecutar el siguiente comando:

[source, console]
----
$ pip install --upgrade pip

----

* Continuamos instalando las siguientes dependencias:

[source, console]
----
$ sudo apt install libtiff5-dev \
                   libjpeg8-dev \
                   zlib1g-dev \
                   libfreetype6-dev \
                   liblcms2-dev \
                   libwebp-dev \
                   tcl8.6-dev \
                   tk8.6-dev \
                   python-tk

----

* y por ultimo, instalamos los complementos necesarios para el correcto
  funcionamiento de python:

[source, console]
----
$ sudo pip install  django \
                    requests \
                    openpyxl \
                    lxml \
                    python-pptx \
                    pyyaml \
                    decorators \
                    retrying

----

<<<
== Descarga

* En esta etapa procedemos a crear una copia local del repositorio central de
  Integrates en una carpeta especifica en el sistema:

[source, console]
----
$ cd /var/www && sudo git clone https://gitlab.com/fluidsignal/integrates.git
Cloning into 'integrates'...
Username for 'https://gitlab.com': loginatfluid
Password for 'https://loginatfluid@gitlab.com':
remote: Counting objects: 5858, done.
remote: Compressing objects: 100% (93/93), done.
remote: Total 5858 (delta 82), reused 148 (delta 69)
Receiving objects: 100% (5858/5858), 29.56 MiB | 679.00 KiB/s, done.
Resolving deltas: 100% (3243/3243), done.
Checking connectivity... done.

----

* El comando anterior descargará todo el repositorio de código completo del
  producto, permitiendo navegar por diferentes versiones y ramas.

<<<
== Configuración GIT

* Para comenzar a realizar cambios sobre el repositorio deben configurarse los
  usuarios con los cuales quedaran registrados sus cambios:

[source, console]
----
$ git config --global user.name "Faustino Asprilla"
$ git config --global user.email fasprilla@fluidattacks.com
----

* Usted puede verificar si los cambios estan registrados mediante la orden:

[source, console]
----
$ git config --list
user.email=fasprilla@fluidattacks.com
user.name=Faustino Asprilla
alias.ahead=log origin/master..HEAD --oneline
push.default=matching
----

<<<
== Desplegar FLUIDintegrates de forma local

* Antes de contribuir al repositorio central de FLUID, es necesario comprobar que
  los cambios que vayamos a realizar funcionen correctamente y no alteren el buen
  funcionamiento del resto del codigo. Esto se puede verifcar al desplegar el app
  de forma local, lo cual se puede lograr a traves de los siguientes comandos:

[source, console]
----
$ sudo  mkdir  /usr/src/app  && cd /usr/src/app
$ sudo ln -s /var/www/integrates/* .

----

* Para instalar las otras dependencias que son requisito minimo para desplegar
  FLUIDIntegrates, ejecute:

[source, console]
----
$ sudo apt install ansible
$ sudo apt-get install libmysqlclient-dev \
                       build-essential \
                       libssl-dev \
                       libffi-dev \
                       python-dev

----

* A continuación se instalarán las dependencias faltantes y se actualizarán
  aquellas que ya están instaladas:

[source, console]
----
$ sudo apt-get install -y python-dev python-pip
$ sudo gem install asciidoctor-pdf --pre
$ cd /var/www/integrates/deploy/containers/deps && sudo pip install --upgrade -r requirements.txt

----

* El anterior comando es esencial para el despliegue, por lo que usted debe
  asegurarse que la instalación sea correcta (Sin mensajes de error o dependencias
  no actualizadas)

<<<
== Instalación de NPM
* Node Package Manager o simplemente npm es un gestor de paquetes desde el cual
  podremos tener cualquier librería disponible con solo una línea de código, npm
  nos ayudará a administrar nuestros módulos, distribuir paquetes y agregar
  dependencias de una manera sencilla. Para instalar npm debemos instalar
  _Nodejs_, este trae por defecto npm:

[source, console]
----
$ sudo apt-get install curl
$ curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
$ sudo apt-get install -y nodejs

----

* Para instalar las dependencias que ya se encuentran en FLUIDIntegrates ejecutar
  el siguiente comando:

[source, console]
----
$ cd app/assets
$ npm install

----

* Para instalar nuevas dependencias o paquetes se debe ejecutar el siguiente comando:

[source, console]
----
$ cd app/assets
$ npm install <package_name> --save

----

* Para borrar dependencias o paquetes que ya no serán utilizados:

[source, console]
----
$ cd app/assets
$ npm uninstall <package_name> --save

----

* Para ver mas información sobre los paquetes de npm visitar el siguiente
link: _https://www.npmjs.com/_.

<<<
== Variables de entorno para Integrates

* El archivo _**.envrc**_ contiene todas las variables de entorno para el correcto funcionamiento de Integrates,
  por razones de seguridad el archivo no se encuentra en el repositorio. Para una copia por favor contactar a
  _jrestrepo@fluidattacks.com_.

* Es necesario agregar la siguiente línea:  _**eval "$(direnv hook bash)"**_  al
  final del archivo que se despliega al ejecutar el comando:

[source, console]
----
$ nano ~/.bashrc

----

* Ubicar el archivo _.envrc_ en la carpeta principal de Integrates, es decir, en la ruta
  /var/www/integrates y luego ejecutar el siguiente comando:

[source, console]
----
$ direnv allow

----

* Para confirmar que las variables fueron correctamente cargadas, ejecute el siguiente comando y verifique
  que se muestren las variables que están en el archivo _.envrc_ .

[source, console]
----
$ printenv

----

<<<
== Crear servidor

* Finalmente se debe lanzar el servidor local que contiene a la aplicación. Esto
  se puede realizar de 2 maneras:

=== 1. Creación de server con Python

[source, console]
----
$ python manage.py runsslserver

----

* En este punto la aplicación ya está desplegada localmente, para acceder a ella
  vaya a la barra de direcciones de su navegador de preferencia y escriba la siguiente
  dirección: _https://localhost:8000_.

=== 1. Creación de server con Docker

* Lo primero que hay que hacer es instalar Docker CE. Seguir los pasos de instalación que se encuentran
  https://docs.docker.com/install/linux/docker-ce/debian/#install-using-the-convenience-script[aquí].

* Ejecutar el siguiente comando, el cual le pedirá que ingrese un usuario y contraseña
  correspondientes a sus credenciales en Gitlab.

[source, console]
----
$ sudo docker login registry.gitlab.com -u $DOCKER_USER -p $DOCKER_PASS

----
* Se debe especificar el nombre de la rama del repositorio de Integrates que se clonará
  dentro del contenedor, usualmente se clona la rama _master_.

[source, console]
----
$ CI_COMMIT_REF_NAME=master

----

* Antes de lanzar el contenedor, es necesario crear la imagen que se utilizará
  durante el despliegue.

[source, console]
----
$ sh build.sh $CI_COMMIT_REF_NAME $FI_GITLAB_LOGIN $FI_GITLAB_PASSWORD $FI_DRIVE_AUTHORIZATION $FI_DOCUMENTROOT $FI_SSL_CERT $FI_SSL_KEY

----

* Para desplegar el servidor con Integrates se ejecuta el siguiente comando:

[source, console]
----
$ sudo docker run -d -p 8000:443 --env-file /var/www/integrates/env.list -t --name=integrates registry.gitlab.com/fluidsignal/integrates:base

----

* En este punto la aplicación ya está desplegada localmente, para acceder a ella
  vaya a la barra de direcciones de su navegador de preferencia y escriba la siguiente
  dirección: _https://localhost:8000_.
