apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: review-__DEPLOYMENT_NAME__
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "WWW-Authenticate: OAuth realm=\"Access to FLUIDIntegrates\" charset=\"UTF-8\"";
      more_set_headers "X-XSS-Protection: 1; mode=block";
      more_set_headers "X-Permitted-Cross-Domain-Policies: master-only";
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "Pragma: no-cache";
      more_set_headers "Expires: 0";
      more_set_headers "Content-Security-Policy: script-src 'self' 'unsafe-inline' 'unsafe-eval' *.amazonaws.com *.cloudfront.net *.mxpnl.com *.cloudflare.com *.cookiebot.com *.intercomcdn.com *.intercom.io https://d2yyd1h5u9mauk.cloudfront.net *.pingdom.net cdn.jsdelivr.net/npm/;";
      gzip "off";
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/app-root: /integrates
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
  - hosts:
    - __DEPLOYMENT_NAME__.integrates.env.fluidattacks.com
    secretName: ssl-certificate
  rules:
  - host: __DEPLOYMENT_NAME__.integrates.env.fluidattacks.com
    http:
      paths:
      - backend:
          serviceName: service-async-__DEPLOYMENT_NAME__
          servicePort: 80
        path: /integrates/apiv2(/|$)(.*)
      - backend:
          serviceName: service-__DEPLOYMENT_NAME__
          servicePort: 80
        path: /integrates(/|$)(.*)
      - backend:
          serviceName: service-__DEPLOYMENT_NAME__
          servicePort: 80
        path: /(assets.*|oauth.*|index.*|registration.*|silk.*|errors.*)(.*)
      - backend:
          serviceName: service-__DEPLOYMENT_NAME__
          servicePort: 80
        path: /
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: review-async-__DEPLOYMENT_NAME__
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "WWW-Authenticate: OAuth realm=\"Access to FLUIDIntegrates\" charset=\"UTF-8\"";
      more_set_headers "X-XSS-Protection: 1; mode=block";
      more_set_headers "X-Permitted-Cross-Domain-Policies: master-only";
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "Pragma: no-cache";
      more_set_headers "Expires: 0";
      more_set_headers "Content-Security-Policy: script-src 'self' 'unsafe-inline' 'unsafe-eval' *.amazonaws.com *.cloudfront.net *.mxpnl.com *.cloudflare.com *.cookiebot.com *.intercomcdn.com *.intercom.io https://d2yyd1h5u9mauk.cloudfront.net *.pingdom.net cdn.jsdelivr.net/npm/;";
      gzip "off";
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/app-root: /integrates
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
  - hosts:
    - __DEPLOYMENT_NAME__-async.integrates.env.fluidattacks.com
    secretName: ssl-certificate
  rules:
  - host: __DEPLOYMENT_NAME__-async.integrates.env.fluidattacks.com
    http:
      paths:
      - backend:
          serviceName: service-async-__DEPLOYMENT_NAME__
          servicePort: 80
        path: /integrates(/|$)(.*)
      - backend:
          serviceName: service-async-__DEPLOYMENT_NAME__
          servicePort: 80
        path: /(assets.*|oauth.*|index.*|registration.*|silk.*|errors.*)(.*)
      - backend:
          serviceName: service-async-__DEPLOYMENT_NAME__
          servicePort: 80
        path: /
