apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: review-$CI_COMMIT_REF_SLUG
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "WWW-Authenticate: OAuth realm=\"Access to FLUIDIntegrates\" charset=\"UTF-8\"";
      more_set_headers "X-XSS-Protection: 1; mode=block";
      more_set_headers "X-Permitted-Cross-Domain-Policies: master-only";
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "Pragma: no-cache";
      more_set_headers "Expires: 0";
      more_set_headers "Content-Security-Policy: script-src 'self' 'unsafe-inline' 'unsafe-eval' *.amazonaws.com *.mxpnl.com *.cloudflare.com *.cookiebot.com *.intercomcdn.com *.intercom.io https://d2yyd1h5u9mauk.cloudfront.net *.pingdom.net cdn.jsdelivr.net/npm/;";
      gzip "off";
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/app-root: /integrates
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
  - hosts:
    - $CI_COMMIT_REF_SLUG.integrates.env.fluidattacks.com
    secretName: ssl-certificate
  rules:
  - host: $CI_COMMIT_REF_SLUG.integrates.env.fluidattacks.com
    http:
      paths:
      - backend:
          serviceName: service-$CI_COMMIT_REF_SLUG
          servicePort: 80
        path: /integrates(.*)
      - backend:
          serviceName: service-$CI_COMMIT_REF_SLUG
          servicePort: 80
        path: /(assets.*|oauth.*|index.*|registration.*|silk.*|errors.*)
      - backend:
          serviceName: service-$CI_COMMIT_REF_SLUG
          servicePort: 80
        path: /dynamo_shell(.*)
      - backend:
          serviceName: service-$CI_COMMIT_REF_SLUG
          servicePort: 80
        path: /
