apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: technology@fluidattacks.com
    dns01:
      providers:
      - name: route53
        route53:
          region: us-east-1
          accessKeyID: __RA_ACCESS_KEY__
          secretAccessKeySecretRef:
            name: ra-aws
            key: sec-key
          hostedZoneID: __DNS_ZONE_ID__
    privateKeySecretRef:
      name: letsencrypt-key
    server: https://acme-v02.api.letsencrypt.org/directory
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ssl-review-apps
spec:
  acme:
    config:
    - dns01:
        provider: route53
      domains:
        - '*.__CI_PROJECT_NAME__.env.fluidattacks.com'
  dnsNames:
  - '*.__CI_PROJECT_NAME__.env.fluidattacks.com'
  issuerRef:
    kind: Issuer
    name: letsencrypt
  secretName: ssl-certificate
