apiVersion: v1
kind: Secret
metadata:
  name: env-secret-__DEPLOYMENT_NAME__
type: Opaque
data:
  AWS_ACCESS_KEY_ID: __B64_AWS_ACCESS_KEY_ID__
  AWS_SECRET_ACCESS_KEY: __B64_AWS_SECRET_ACCESS_KEY__
  JWT_TOKEN: __B64_JWT_TOKEN__
