= Documentacion Proyecto oka

== *FIN.0001. Inyeccin SQL*

=== Vulnerabilidad
Se generan sentencias SQL dinmicas sin la validacin requerida de datos y sin utilizar sentencias parametrizadas o procedimientos almacenados.

=== Amenaza
Un usuario autorizado en la aplicacin puede inyectar sentencias SQL, con la posibilidad de obtener informacin sobre la base de datos, as como extraer, modificar y/o borrar informacin de la misma
.

=== Riesgo
Probabilidad de que un usuario autorizado ejecute sentencias SQL debido a que la aplicacin no valida los datos ingresados por el usuario lo que permite la inyeccin de sentencias SQL dinmicas en algunos de sus campos, lo que puede ocasionar que se extraiga, modifique o borre la informacin almacenada en la base de datos de la aplicacin

=== Donde
AFGNPLIFAJ.TXT:58,86

=== Recomendacion
Realizar las consultas a la base de datos por medio de sentencias o procedimientos parametrizados.
= Documentacion Proyecto oka

== *FIN.0068. Condicionales sin opcin por defecto*

=== Vulnerabilidad
El cdigo presenta  condicionales sin ninguna opcin por defecto, ejemplo: se tiene un case  que no contempla una opcin a seguir en caso de que no se cumpla la condicin.

=== Amenaza
Un usuario vlido en la aplicacin puede experimentar comportamientos inesperados en la aplicacin debido a que no se encuentran definidas salidas por defecto.


=== Riesgo
Probabilidad de que un usuario vlido en la aplicacin experimente comportamientos inesperados en el uso de la aplicacin debido a que no se encuentran definidas salidas por defecto en algunas sentencias de cdigo lo que puede ocasionar indisponibilidad o errores inesperados.


=== Donde
ARCARACSC.txt
ARCICLOSC.txt
ARMDBCAUC.txt
AROPERAVC.txt
ARSINDISC.txt
LSCAMPINFR.txt
LSCARACSC.txt
LSCICLOSC.txt
LSENACDEWR.txt
LSENANX6WR.txt
LSENANXMWJ.txt
LSENANXMWR.txt
LSENASALWJ.txt
LSENASALWR.txt
LSENCAPLWR.txt
LSENCCASWR.txt
AFGNPLIFAJ.TXT

=== Recomendacion
Definir una opcin por defecto para las sentencias que an no cuentan con esta.
