apiVersion: v1
kind: Secret
metadata:
  name: integrates-env
  namespace: serves
type: Opaque
data:
  VAULT_HOST: $VAULT_HOST
  VAULT_TOKEN: $VAULT_TOKEN
  VAULT_PORT: NDQz
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: integrates
  namespace: serves
  annotations:
    kubernetes.io/change-cause: "New deployment version of Integrates on $DATE"
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: integrates
    spec:
      containers:
      - name: container-integrates
        image: registry.gitlab.com/fluidattacks/integrates:app
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: integrates-env
        env:
          - name: DEPLOYMENT_DATE
            value: "$DATE"
          - name: INSTANA_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        ports:
        - containerPort: 80
        readinessProbe:
          exec:
            command:
              - sh
              - -ce
              - "curl -sS http://localhost | grep 'FluidIntegrates'"
          initialDelaySeconds: 20
          periodSeconds: 5
          successThreshold: 3
          failureThreshold: 10
      imagePullSecrets:
      - name: gitlab-reg
---
apiVersion: v1
kind: Service
metadata:
  name: integrates
  namespace: serves
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: integrates
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: integrates-bot
  namespace: serves
  annotations:
    kubernetes.io/change-cause: "New deployment version of Integrates Bot on $DATE"
spec:
  minReadySeconds: 15
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: integrates-bot
    spec:
      containers:
      - name: container-integrates-bot
        image: registry.gitlab.com/fluidsignal/default/integrates/bot:master
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: integrates-env
        env:
          - name: DEPLOYMENT_DATE
            value: "$DATE"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: gitlab-reg
---
apiVersion: v1
kind: Service
metadata:
  name: integrates-bot
  namespace: serves
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: integrates-bot
