type: map
mapping:
  inputs:
    type: seq
    sequence:
      - type: map
        mapping:
          field:
            type: str
            required: true
          state:
            type: str
            enum: ['open', 'closed']
            required: true
          url:
            type: str
            required: true
  lines:
    type: seq
    sequence:
      - type: map
        mapping:
          line:
            type: str
            pattern: ^[0-9]+(?:-[0-9]+)?(,[0-9]+(?:-[0-9]+)?)*$
            required: true
          path:
            type: str
            pattern: ^([^/][^/]+/([^/]+/?)+)|([^\\]+\\([^\\]+\\?)+)|^([^/]+)$
            required: true
          state:
            type: str
            enum: ['open', 'closed']
            required: true
  ports:
    type: seq
    sequence:
      - type: map
        mapping:
          host:
            type: str
            required: true
          port:
            type: str
            pattern: ^[0-9]+(?:-[0-9]+)?(,[0-9]+(?:-[0-9]+)?)*$
            required: true
          state:
            type: str
            enum: ['open', 'closed']
            required: true
